NDefines.NBuildings.MAX_SHARED_SLOTS = 1000

NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 25
NDefines.NProduction.RAILWAY_GUN_MAX_MIL_FACTORIES_PER_LINE = 10
NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 50
NDefines.NProduction.FLOATING_HARBOR_MAX_NAV_FACTORIES_PER_LINE = 50
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 50
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 50

NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 365

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 10000
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 10000
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 10000

--Spot optimization mod

NDefines.NGame.GAME_SPEED_SECONDS = { 1.0, 0.25, 0.15, 0.05, 0.0 }

NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 1000
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 100
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 30
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 36

NDefines_Graphics.NMapIcons.STRATEGIC_AIR_PRIORITY_AIR_MISSION = 290
NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {300, 500, 1500}

NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_BASE = 100
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_TRASHHOLD = 0
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_PENALTY = 0
NDefines.NAI.GIVE_STATE_CONTROL_MIN_CONTROLLED = 0
NDefines.NAI.GIVE_STATE_CONTROL_MIN_CONTROL_DIFF = 0